const express = require('express');
const router = express.Router();
const { authLimiter } = require('../../middleware/rateLimiter');

const authRoutes = require('./auth.routes');
const usersRoutes = require('./users.routes');
const vehiclesRoutes = require('./vehicles.routes');
const ridesRoutes = require('./rides.routes');
const tripsRoutes = require('./trips.routes');
const messagesRoutes = require('./messages.routes');
const reviewsRoutes = require('./reviews.routes');
const privacyRoutes = require('./privacy.routes');
const uploadsRoutes = require('./uploads.routes');
const adminRoutes = require('./admin.routes');
const paymentsRoutes = require('./payments.routes');
const bookingsRoutes = require('./bookings.routes');
const driverDocumentsRoutes = require('./driver.documents.routes');
const vehicleDocumentsRoutes = require('./vehicle.documents.routes');
const paymentMethodsRoutes = require('./payment-methods.routes');
const ownerRoutes = require('./owner.routes');
const fleetRoutes = require('./fleet.routes');
const ownerDocumentsRoutes = require('./owner.documents.routes');
const payoutRoutes = require('./payout.routes');
const devicesRoutes = require('./devices.routes');

router.use('/auth', authLimiter.middleware(), authRoutes);
router.use('/users', usersRoutes);
router.use('/vehicles', vehiclesRoutes);
router.use('/rides', ridesRoutes);
router.use('/trips', tripsRoutes);
router.use('/messages', messagesRoutes);
router.use('/reviews', reviewsRoutes);
router.use('/privacy', privacyRoutes);
router.use('/uploads', uploadsRoutes);
router.use('/admin', adminRoutes);
router.use('/payments', paymentsRoutes);
router.use('/bookings', bookingsRoutes);
router.use('/driver-documents', driverDocumentsRoutes);
router.use('/vehicle-documents', vehicleDocumentsRoutes);
router.use('/payment-methods', paymentMethodsRoutes);
router.use('/owner', ownerRoutes);
router.use('/fleet', fleetRoutes);
router.use('/owner-documents', ownerDocumentsRoutes);
router.use('/payout', payoutRoutes);
router.use('/devices', devicesRoutes);

module.exports = router;
