module.exports = {
  DRIVER_DOCUMENT_TYPES: {
    AADHAAR: 'AADHAAR',
    PAN: 'PAN',
    PASSPORT_PHOTO: 'PASSPORT_PHOTO',
    DRIVING_LICENSE: 'DRIVING_LICENSE',
    POLICE_VERIFICATION: 'POLICE_VERIFICATION',
    BANK_DETAILS: 'BANK_DETAILS',
    BADGE: 'BADGE',
    MEDICAL_FITNESS: 'MEDICAL_FITNESS'
  },
  VEHICLE_DOCUMENT_TYPES: {
    RC: 'RC',
    PERMIT: 'PERMIT',
    INSURANCE: 'INSURANCE',
    FITNESS_CERTIFICATE: 'FITNESS_CERTIFICATE',
    PUC: 'PUC',
    FASTAG: 'FASTAG'
  },
  DOC_STATUS: {
    PENDING: 'PENDING',
    UPLOADED: 'UPLOADED',
    UNDER_REVIEW: 'UNDER_REVIEW',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    EXPIRED: 'EXPIRED'
  },
  VEHICLE_TYPES: {
    SEDAN: 'SEDAN',
    SUV: 'SUV',
    HATCHBACK: 'HATCHBACK',
    MINIVAN: 'MINIVAN',
    TEMPO: 'TEMPO',
    MOTORCYCLE: 'MOTORCYCLE',
    AUTO: 'AUTO',
    EV_SEDAN: 'EV_SEDAN',
    EV_SUV: 'EV_SUV',
    EV_HATCHBACK: 'EV_HATCHBACK',
    EV_AUTO: 'EV_AUTO',
    EV_MOTORCYCLE: 'EV_MOTORCYCLE',
    LUXURY: 'LUXURY',
    PREMIUM: 'PREMIUM',
    ECONOMY: 'ECONOMY',
    PICKUP: 'PICKUP',
    TRUCK: 'TRUCK',
    VAN: 'VAN'
  },
  OWNER_DOCUMENT_TYPES: {
    GST: 'GST',
    PAN: 'PAN',
    BUSINESS_LICENSE: 'BUSINESS_LICENSE',
    ADDRESS_PROOF: 'ADDRESS_PROOF'
  }
};
