module.exports = {
  RIDE_STATUS: {
    ACTIVE: 'ACTIVE',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED'
  },
  TRIP_STATUS: {
    SCHEDULED: 'SCHEDULED',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED'
  },
  REQUEST_STATUS: {
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    CANCELLED: 'CANCELLED'
  },
  REVIEW_TYPE: {
    DRIVER_TO_RIDER: 'DRIVER_TO_RIDER',
    RIDER_TO_DRIVER: 'RIDER_TO_DRIVER'
  }
};
